FROM golang

WORKDIR /go/src/app

RUN go install github.com/canthefason/go-watcher/cmd/watcher@latest

COPY go.mod go.sum ./

RUN go mod download

ADD . .

EXPOSE 8000

ENTRYPOINT watcher -run /go/src/app/main.go -watch app