#!/bin/bash

export DOCKER_BUILDKIT=1

docker build -t "$IMAGE_NAME":"$VERSION" . || exit 1
docker image tag "$IMAGE_NAME":"$VERSION" "$IMAGE_NAME":"$IMAGE_TAG" || exit 1

yq e -i '.version = strenv(CHART_VERSION)' charts/logging-pipeline-plumber/Chart.yaml
yq e -i '.appVersion = "v" + strenv(CHART_VERSION)' charts/logging-pipeline-plumber/Chart.yaml

helm package charts/logging-pipeline-plumber -d dist/
